//! The generated reference in docs/spec/operations.md (interfaces.md#parity-test):
//! rendered from the registry's catalogue, and failing when the committed copy
//! is stale. `UPDATE_DOCS=1 cargo test --test docs` rewrites it.

use std::{collections::BTreeMap, fmt::Write, path::Path};

use serde_json::Value;

const BEGIN: &str = "<!-- generated by tests/docs.rs: do not edit by hand -->";
const END: &str = "<!-- end generated -->";

/// A schema's type, short: `string`, `string[]`, `path \| title`, `Filter`.
fn type_of(schema: &Value, defs: &Value, named: &mut BTreeMap<String, Value>) -> String {
    if let Some(name) = schema["$ref"].as_str().and_then(|r| r.rsplit('/').next()) {
        let def = &defs[name];
        if def["enum"].is_array() || def["oneOf"].is_array() {
            return type_of(def, defs, named);
        }
        named.insert(name.to_string(), def.clone());
        return format!("`{name}`");
    }
    if let Some(values) = schema["enum"].as_array() {
        return values
            .iter()
            .map(|v| format!("`{}`", v.as_str().unwrap_or_default()))
            .collect::<Vec<_>>()
            .join(" \\| ");
    }
    if let Some(variants) = schema["oneOf"].as_array().or(schema["anyOf"].as_array()) {
        return variants
            .iter()
            .filter(|v| v["type"] != "null")
            .map(|v| match v["const"].as_str() {
                Some(c) => format!("`{c}`"),
                None => type_of(v, defs, named),
            })
            .collect::<Vec<_>>()
            .join(" \\| ");
    }
    let ty = match &schema["type"] {
        Value::String(t) => t.as_str(),
        Value::Array(ts) => ts
            .iter()
            .filter_map(Value::as_str)
            .find(|t| *t != "null")
            .unwrap_or("any"),
        _ => "any",
    };
    match ty {
        "array" => format!("{}[]", type_of(&schema["items"], defs, named)),
        "object" => "object".to_string(),
        other => other.to_string(),
    }
}

fn one_line(text: &str) -> String {
    text.split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace('|', "\\|")
}

/// `| field | type | description |` rows for an object schema; `?` marks optional fields.
fn fields(schema: &Value, defs: &Value, named: &mut BTreeMap<String, Value>) -> String {
    let required: Vec<&str> = schema["required"]
        .as_array()
        .into_iter()
        .flatten()
        .filter_map(Value::as_str)
        .collect();
    let mut out = String::new();
    for (name, field) in schema["properties"].as_object().into_iter().flatten() {
        let mark = if required.contains(&name.as_str()) {
            ""
        } else {
            "?"
        };
        let _ = writeln!(
            out,
            "| `{name}{mark}` | {} | {} |",
            type_of(field, defs, named),
            one_line(field["description"].as_str().unwrap_or_default())
        );
    }
    out
}

fn reference(catalogue: &Value) -> String {
    let mut out = String::new();
    let mut named = BTreeMap::new();
    for op in catalogue["operations"].as_array().unwrap() {
        let input = &op["input_schema"];
        let _ = writeln!(
            out,
            "### `{}` ({})\n\n{}\n",
            op["name"].as_str().unwrap(),
            op["kind"].as_str().unwrap(),
            one_line(op["description"].as_str().unwrap())
        );
        let rows = fields(input, &input["$defs"], &mut named);
        if rows.is_empty() {
            out += "No inputs.\n\n";
        } else {
            let _ = write!(
                out,
                "| Input | Type | Description |\n|---|---|---|\n{rows}\n"
            );
        }
        let output: Vec<String> = op["output_schema"]["properties"]
            .as_object()
            .into_iter()
            .flatten()
            .map(|(name, _)| format!("`{name}`"))
            .collect();
        let _ = writeln!(out, "Output: {}.\n", output.join(", "));
    }
    out += "### Input types\n\n";
    // Named types can refer to more named types: render until none are new.
    let mut done: BTreeMap<String, String> = BTreeMap::new();
    while let Some((name, def)) = named.iter().find(|(n, _)| !done.contains_key(*n)) {
        let (name, def) = (name.clone(), def.clone());
        let mut more = BTreeMap::new();
        let text = format!(
            "**`{name}`**: {}\n\n| Field | Type | Description |\n|---|---|---|\n{}",
            one_line(def["description"].as_str().unwrap_or_default()),
            fields(&def, &Value::Null, &mut more)
        );
        done.insert(name, text);
        for (n, d) in more {
            named.entry(n).or_insert(d);
        }
    }
    out += &done.into_values().collect::<Vec<_>>().join("\n");
    out
}

#[test]
fn the_generated_reference_in_operations_md_is_current() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("docs/spec/operations.md");
    let doc = std::fs::read_to_string(&path)
        .unwrap()
        .replace("\r\n", "\n");
    let generated = reference(&wikirs_core::catalogue());
    let (before, rest) = doc.split_once(BEGIN).expect("the begin marker");
    let (current, after) = rest.split_once(END).expect("the end marker");
    let fresh = format!("\n\n{generated}\n");
    if current == fresh {
        return;
    }
    if std::env::var_os("UPDATE_DOCS").is_some() {
        std::fs::write(&path, format!("{before}{BEGIN}{fresh}{END}{after}")).unwrap();
        return;
    }
    panic!("docs/spec/operations.md is stale: run `UPDATE_DOCS=1 cargo test --test docs`");
}
