[package]
name = "wikirs-cli"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
wikirs-core = { workspace = true, features = ["clap"] }
clap.workspace = true
serde_json.workspace = true
similar.workspace = true
base64.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
